ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS height_cm NUMERIC(6, 2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS activity_level NUMERIC(4, 2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS target_weight_kg NUMERIC(6, 2);
